version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        WITH_XDEBUG: "true"
    image: smartcrm_php:8.4
    container_name: smartcrm_app
    working_dir: /var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      PUID: ${UID}
      PGID: ${GID}
      XDEBUG_MODE: debug
    volumes:
      - ./app:/var/www/html:delegated
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - smartcrm_net
    depends_on:
      - mysql

  nginx:
    image: nginx:stable
    container_name: smartcrm_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/certs/smartcrm.pem:/etc/ssl/certs/smartcrm.pem:ro
      - ./docker/certs/smartcrm-key.pem:/etc/ssl/private/smartcrm-key.pem:ro
    networks:
      - smartcrm_net
    depends_on:
      - app

  mysql:
    image: mysql:8.2
    container_name: smartcrm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: smartcrm_ecommerce_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3306:3306"
    networks:
      - smartcrm_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smartcrm_phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    networks:
      - smartcrm_net
    depends_on:
      - mysql

networks:
  smartcrm_net:
    driver: bridge

volumes:
  mysql_data:
